import { Inter } from 'next/font/google'
import './globals.scss'
import BodyLayout from './bodyLayout'
import { MyStoreProvider } from './context/store'

const inter = Inter({ subsets: ['latin'] })

 export const metadata = {
  title: 'Gestion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
    <MyStoreProvider>
      <BodyLayout interClassName={inter.className}>
        {children}
      </BodyLayout>
      </MyStoreProvider>
    </html>
  )
}
