import { Inter } from 'next/font/google'
import '@/src/styles/globals.scss'
import { MyStoreProvider } from '@/context/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gestion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <MyStoreProvider>
         {children}
      </MyStoreProvider>
      </body>
      
    </html>
  )
}
