import { Inter } from 'next/font/google'
import '../../public/styles/globals.scss'
import { MyStoreProvider } from '../../src/app/context/store'
import Navbar from './components/layouts/Navbar'
import SideBar from './components/layouts/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gestion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        <section className="body">
          <SideBar />
          <section className="contents">
            <MyStoreProvider>
              {children}
            </MyStoreProvider>
          </section>
        </section>


      </body>

    </html>
  )
}
